<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExpenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('expenses')->insert([
            0 => [
                'id' => '1',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '10561.68',
                'comment' => '',
                'date' => '3/1/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            1 => [
                'id' => '2',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '10523.49',
                'comment' => '',
                'date' => '3/2/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            2 => [
                'id' => '3',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '11614.82',
                'comment' => '',
                'date' => '3/3/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            3 => [
                'id' => '4',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '12187.73',
                'comment' => '',
                'date' => '3/4/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            4 => [
                'id' => '5',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '11084.16',
                'comment' => '',
                'date' => '3/5/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            5 => [
                'id' => '6',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '10412.23',
                'comment' => '',
                'date' => '3/6/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            6 => [
                'id' => '7',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '7640.86',
                'comment' => '',
                'date' => '3/7/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            7 => [
                'id' => '8',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6832.1',
                'comment' => '',
                'date' => '3/8/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            8 => [
                'id' => '9',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6127.99',
                'comment' => '',
                'date' => '3/9/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            9 => [
                'id' => '10',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6683.67',
                'comment' => '',
                'date' => '3/10/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            10 => [
                'id' => '11',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6969.78',
                'comment' => '',
                'date' => '3/11/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            11 => [
                'id' => '12',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6076.12',
                'comment' => '',
                'date' => '3/12/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            12 => [
                'id' => '13',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6852.4',
                'comment' => '',
                'date' => '3/13/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            13 => [
                'id' => '14',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6556.48',
                'comment' => '',
                'date' => '3/14/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            14 => [
                'id' => '15',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6313.35',
                'comment' => '',
                'date' => '3/15/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            15 => [
                'id' => '16',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6485.77',
                'comment' => '',
                'date' => '3/16/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            16 => [
                'id' => '17',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '7510.36',
                'comment' => '',
                'date' => '3/17/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            17 => [
                'id' => '18',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '8176.73',
                'comment' => '',
                'date' => '3/18/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            18 => [
                'id' => '19',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '8892.82',
                'comment' => '',
                'date' => '3/19/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            19 => [
                'id' => '20',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '8823.17',
                'comment' => '',
                'date' => '3/20/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            20 => [
                'id' => '21',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '8183.54',
                'comment' => '',
                'date' => '3/21/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            21 => [
                'id' => '22',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '7077.68',
                'comment' => '',
                'date' => '3/22/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            22 => [
                'id' => '23',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6579.92',
                'comment' => '',
                'date' => '3/23/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            23 => [
                'id' => '24',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '6555.02',
                'comment' => '',
                'date' => '3/24/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            24 => [
                'id' => '25',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '7786.15',
                'comment' => '',
                'date' => '3/25/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            25 => [
                'id' => '26',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '7726.74',
                'comment' => '',
                'date' => '3/26/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            26 => [
                'id' => '27',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '7066.6',
                'comment' => '',
                'date' => '3/27/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            27 => [
                'id' => '28',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '8010.3',
                'comment' => '',
                'date' => '3/28/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            28 => [
                'id' => '29',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '8115.03',
                'comment' => '',
                'date' => '3/29/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            29 => [
                'id' => '30',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '9015.3',
                'comment' => '',
                'date' => '3/30/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            30 => [
                'id' => '31',
                'user_id' => '1',
                'expense_category_id' => '1',
                'source_id' => '',
                'amount' => '9015.3',
                'comment' => '',
                'date' => '3/31/2022',
                'type_of_sum' => '0',
                'type_variable' => '0',
                'from_file' => true,
            ],
            31 => [
                'id' => '32',
                'user_id' => '1',
                'expense_category_id' => '',
                'source_id' => '',
                'amount' => '55',
                'comment' => '',
                'date' => '3/1/2022',
                'type_of_sum' => '0',
                'type_variable' => '1',
                'from_file' => false,
                'created_at' => '4/8/2022 7:10',
                'updated_at' => '4/8/2022 7:10',
            ],
            32 => [
                'id' => '33',
                'user_id' => '1',
                'expense_category_id' => '',
                'source_id' => '',
                'amount' => '620000',
                'comment' => '',
                'date' => '4/1/2022',
                'type_of_sum' => '1',
                'type_variable' => '0',
                'from_file' => false,
                'created_at' => '4/8/2022 7:11',
                'updated_at' => '4/8/2022 7:24',
            ],
            33 => [
                'id' => '34',
                'user_id' => '1',
                'expense_category_id' => '',
                'source_id' => '',
                'amount' => '3',
                'comment' => '',
                'date' => '3/1/2022',
                'type_of_sum' => '2',
                'type_variable' => '0',
                'from_file' => false,
                'created_at' => '4/8/2022 12:49',
                'updated_at' => '4/8/2022 12:49',
            ],
        ]);

        //
    }
}
