<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExpenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('expenses')->insert([
             [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 10561.68,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/1/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 10523.49,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/2/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 11614.82,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/3/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 12187.7,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/4/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 11084.16,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/5/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 10412.23,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/6/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 7640.86,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/7/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6832.1,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/8/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6127.99,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/9/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6683.67,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/10/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6969.78,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/11/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6076.12,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/12/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6852.4,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/13/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6556.48,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/14/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6313.35,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/15/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6485.77,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/16/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 7510.36,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/17/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 8176.73,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/19/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 8892.82,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/19/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 8823.17,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/20/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 8183.54,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/21/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 7077.68,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/22/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6579.92,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/23/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 6555.02,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/24/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 7786.15,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/25/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 7726.74,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/26/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 7066.6,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/27/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 8010.3,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/28/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 8115.03,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/29/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 9015.3,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/30/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => 1,
                'source_id' => '',
                'amount' => 9015.3,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/31/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 0,
                'from_file' => true,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => '',
                'source_id' => '',
                'amount' => 55,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/1/2022')->format('Y-m-d'),
                'type_of_sum' => 0,
                'type_variable' => 1,
                'from_file' => false,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => '',
                'source_id' => '',
                'amount' => 620000,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/1/2022')->format('Y-m-d'),
                'type_of_sum' => 1,
                'type_variable' => 0,
                'from_file' => false,
            ],
            [
                'user_id' => 1,
                'expense_category_id' => '',
                'source_id' => '',
                'amount' => 3,
                'comment' => '',
                'date' => Carbon::createFromFormat('m/d/Y', '3/1/2022')->format('Y-m-d'),
                'type_of_sum' => '',
                'type_variable' => 2,
                'from_file' => false,
            ],
        ]);

        //
    }
}
